import re

def reverse_dp(text):
    text = text.replace('ˈ','')
    text = text.replace('ɛ','e')
    text = text.replace('j','i')
    text = text.replace('ɔ','o')
    text = text.replace('w','u')
    text = text.replace('z','s')
    text = text.replace('ds','z')
    text = text.replace('ts','z')
    text = text.replace('dʒ','ʤ')
    text = text.replace('tʃ','ʧ')
    text = text.replace('ːː','ː')
    while re.search("[^ɲʎʃ]ː",text):
        double = re.search("[^ɲʎʃ]ː",text).group()
        text = text.replace(double, double[0]*2)
    text = text.replace('ː','')
    text = text.replace('gi','ghi')
    text = text.replace('ge','ghe')
    text = text.replace('ki','chi')
    text = text.replace('ke','che')
    text = text.replace('k','c')
    text = text.replace('ʤʤi','ggi')
    text = text.replace('ʤi','gi')
    text = text.replace('ʤʤe','gge')
    text = text.replace('ʤe','ge')
    text = text.replace('ʤʤ','ggi')
    text = text.replace('ʤ','gi')
    text = text.replace('ʧʧi','cci')
    text = text.replace('ʧi','ci')
    text = text.replace('ʧʧe','cce')
    text = text.replace('ʧe','ce')
    text = text.replace('ʧʧ','cci')
    text = text.replace('ʧ','ci')
    text = text.replace('ʃi','sci')
    text = text.replace('ʃe','sce')
    text = text.replace('ʃ','sci')
    text = text.replace('ɲ','gn')
    text = text.replace('ʎi','gli')
    text = text.replace('ʎ','gli')
    return text
